export default function Terms({ onBack }) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50">
      <nav className="flex justify-between items-center px-8 py-5 border-b border-gray-100 bg-white/60 backdrop-blur">
        <div className="flex items-center gap-2">
          <img src="/logo-icon.svg" alt="NutriCart" className="h-9 w-9" />
          <span className="text-xl font-bold text-green-700">NutriCart</span>
        </div>
        <button
          onClick={onBack}
          className="text-gray-500 hover:text-green-700 text-sm font-medium transition">
          ← Back
        </button>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-14">
        <h1 className="text-4xl font-extrabold text-gray-800 mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: 3 May 2026</p>

        <div className="space-y-8 text-gray-600 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">1. Acceptance of Terms</h2>
            <p>By creating an account or using NutriCart ("Service"), you agree to these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">2. Description of Service</h2>
            <p>NutriCart provides AI-generated personalised nutrition plans, meal planning, and grocery shopping list recommendations. The Service is provided for informational and convenience purposes only.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">3. Not Medical Advice</h2>
            <p className="font-semibold text-orange-600">NutriCart is not a medical service. Content generated by NutriCart, including meal plans and nutrition targets, is for general informational purposes only and does not constitute medical, dietary, or clinical advice.</p>
            <p className="mt-2">Always consult a qualified healthcare professional or registered dietitian before making significant changes to your diet, especially if you have a medical condition, allergy, or are taking medication.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">4. User Accounts</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must be at least 16 years old to use NutriCart.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You must provide accurate information when creating your profile.</li>
              <li>One account per person — do not share accounts.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Use the Service for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the API.</li>
              <li>Submit false health data to manipulate AI-generated recommendations.</li>
              <li>Resell or redistribute NutriCart content without permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">6. AI-Generated Content</h2>
            <p>Meal plans, recipes, and shopping lists are generated by AI (Anthropic Claude). While we strive for accuracy, AI-generated content may occasionally be incorrect or incomplete. We do not guarantee that:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Nutritional values are 100% accurate.</li>
              <li>All listed products are in stock at your selected store.</li>
              <li>Meal plans are appropriate for all individuals.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">7. Intellectual Property</h2>
            <p>The NutriCart platform, branding, and code are owned by NutriCart. AI-generated meal plans and shopping lists created for you are yours to use personally. You may not reproduce or distribute NutriCart's platform or underlying technology.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, NutriCart is not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including health outcomes resulting from following AI-generated meal plans.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">9. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these Terms. You may delete your account at any time from your account settings.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Continued use of NutriCart after changes constitutes acceptance of the updated Terms. We will notify you of material changes by email.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">11. Governing Law</h2>
            <p>These Terms are governed by the laws of the European Union and the Slovak Republic. Any disputes shall be resolved in the competent courts of Slovakia.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-800 mb-3">12. Contact</h2>
            <p>Questions about these Terms? Email us at <a href="mailto:legal@nutricart.app" className="text-green-600 hover:underline">legal@nutricart.app</a>.</p>
          </section>

        </div>
      </div>

      <footer className="text-center py-6 text-gray-400 text-sm">
        © 2026 NutriCart · <button onClick={onBack} className="hover:text-green-600 transition">Back to home</button>
      </footer>
    </div>
  )
}
